/*
Script de creacion de bases de datos.
*/
LEANGER
/*
Creacion de Usuario SysDBA
*/
CREATE USER SysDBA FROM DBC AS PERM = 0, PASSWORD = ******** ;

/* Bases de LEANGER  */

CREATE DATABASE LEANGER_DW FROM SysDBA AS PERM = 0;

/* Bases de Usuarios LEANGER  */

CREATE DATABASE MDW_USERS FROM LEANGER_DW AS PERM = 0;

/* Bases de LEANGER desarrollo */

CREATE DATABASE MDW_DS FROM LEANGER_DW AS PERM = 0;
/* Base de tablas */
CREATE DATABASE MDW_DS_TABLES FROM MDW_DS AS PERM = 0;
/* Base de vistas */
CREATE DATABASE MDW_DS_VIEWS FROM MDW_DS AS PERM = 0;
/* Base de staging */
CREATE DATABASE MDW_DS_STG FROM MDW_DS AS PERM = 0;

/* Bases de LEANGER homologacion */

CREATE DATABASE MDW_HM FROM LEANGER_DW AS PERM = 0;
/* Base de tablas */
CREATE DATABASE MDW_HM_TABLES FROM MDW_HM AS PERM = 0;
/* Base de vistas */
CREATE DATABASE MDW_HM_VIEWS FROM MDW_HM AS PERM = 0;
/* Base de staging */
CREATE DATABASE MDW_HM_STG FROM MDW_HM AS PERM = 0;

/* Bases de LEANGER produccion */

CREATE DATABASE MDW_PR FROM LEANGER_DW AS PERM = 0;
/* Base de tablas */
CREATE DATABASE MDW_PR_TABLES FROM MDW_PR AS PERM = 0;
/* Base de vistas */
CREATE DATABASE MDW_PR_VIEWS FROM MDW_PR AS PERM = 0;
/* Base de staging */
CREATE DATABASE MDW_PR_STG FROM MDW_PR AS PERM = 0;

/*  permisos de select */

GRANT SELECT ON MDW_PR_TABLES TO MDW_PR_VIEWS WITH GRANT OPTION;
GRANT SELECT ON MDW_HM_TABLES TO MDW_HM_VIEWS WITH GRANT OPTION;
GRANT SELECT ON MDW_DS_TABLES TO MDW_DS_VIEWS WITH GRANT OPTION;

/* Rol de web */
CREATE ROLE MDW_USER_PR_RL;

CREATE ROLE MDW_LOAD_PR_RL;

CREATE ROLE MDW_USER_DS_RL;

CREATE ROLE MDW_LOAD_DS_RL;

CREATE ROLE MDW_USER_HM_RL;

CREATE ROLE MDW_LOAD_HM_RL;

/* Solo consulta bases preexistentes */

GRANT SELECT ON MDW_PR_TABLES TO MDW_USER_PR_RL; /* Tablas*/
GRANT SELECT ON MDW_PR_VIEWS TO MDW_USER_PR_RL; /* Vistas */
GRANT SELECT ON MDW_PR_STG TO MDW_USER_PR_RL; /* Staging */

GRANT SELECT ON MDW_HM_TABLES TO MDW_USER_HM_RL; /* Tablas*/
GRANT SELECT ON MDW_HM_VIEWS TO MDW_USER_HM_RL; /* Vistas */
GRANT SELECT ON MDW_HM_STG TO MDW_USER_HM_RL; /* Staging */

GRANT SELECT ON MDW_DS_TABLES TO MDW_USER_DS_RL; /* Tablas*/
GRANT SELECT ON MDW_DS_VIEWS TO MDW_USER_DS_RL; /* Vistas */
GRANT SELECT ON MDW_DS_STG TO MDW_USER_DS_RL; /* Staging */


GRANT SELECT ON MDW_PR_TABLES TO MDW_LOAD_PR_RL; /* Tablas*/
GRANT SELECT ON MDW_PR_VIEWS TO MDW_LOAD_PR_RL; /* Vistas */
GRANT SELECT ON MDW_PR_STG TO MDW_LOAD_PR_RL; /* Staging */

GRANT SELECT ON MDW_HM_TABLES TO MDW_LOAD_HM_RL; /* Tablas*/
GRANT SELECT ON MDW_HM_VIEWS TO MDW_LOAD_HM_RL; /* Vistas */
GRANT SELECT ON MDW_HM_STG TO MDW_LOAD_HM_RL; /* Staging */

GRANT SELECT ON MDW_DS_TABLES TO MDW_LOAD_DS_RL; /* Tablas*/
GRANT SELECT ON MDW_DS_VIEWS TO MDW_LOAD_DS_RL; /* Vistas */
GRANT SELECT ON MDW_DS_STG TO MDW_LOAD_DS_RL; /* Staging */


GRANT EXECUTE PROCEDURE ON MDW_PR_TABLES TO MDW_USER_PR_RL; /* Execute procedure */
GRANT EXECUTE PROCEDURE ON MDW_HM_TABLES TO MDW_USER_HM_RL; /* Execute procedure */
GRANT EXECUTE PROCEDURE ON MDW_DS_TABLES TO MDW_USER_DS_RL; /* Execute procedure */

GRANT EXECUTE PROCEDURE ON MDW_PR_TABLES TO MDW_LOAD_PR_RL; /* Execute procedure */
GRANT EXECUTE PROCEDURE ON MDW_HM_TABLES TO MDW_LOAD_HM_RL; /* Execute procedure */
GRANT EXECUTE PROCEDURE ON MDW_DS_TABLES TO MDW_LOAD_DS_RL; /* Execute procedure */


/* Actualiza base propia */
GRANT
EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE ON MDW_PR_TABLES TO MDW_USER_PR_RL;

GRANT
EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE ON MDW_HM_TABLES TO MDW_USER_HM_RL;

GRANT
EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE ON MDW_DS_TABLES TO MDW_USER_DS_RL;


GRANT
EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE ON MDW_PR_TABLES TO MDW_LOAD_PR_RL;

GRANT
EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE ON MDW_HM_TABLES TO MDW_LOAD_HM_RL;

GRANT
EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE ON MDW_DS_TABLES TO MDW_LOAD_DS_RL;


/* Base de staging para LEANGER. GERMAN 2016-10-02 */
GRANT

CREATE MACRO,
CREATE TABLE,
CREATE VIEW,

DROP MACRO,
DROP TABLE,
DROP VIEW,

EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE

ON MDW_PR_STG TO MDW_LOAD_PR_RL;

GRANT

CREATE MACRO,
CREATE TABLE,
CREATE VIEW,

DROP MACRO,
DROP TABLE,
DROP VIEW,

EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE

ON MDW_HM_STG TO MDW_LOAD_HM_RL;

GRANT

CREATE MACRO,
CREATE TABLE,
CREATE VIEW,

DROP MACRO,
DROP TABLE,
DROP VIEW,

EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE

ON MDW_DS_STG TO MDW_LOAD_DS_RL;


CREATE PROFILE MDW_WEB_PRF AS SPOOL = 5000000000 BYTES; -- 5. GB.

/* Usuarios de WEB. */

CREATE USER MDW_WEB_USERS FROM MDW_USERS AS PERM = 0, PASSWORD = ******** ;

--USER

CREATE USER web_user_pr FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_USER_PR_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;

CREATE USER web_user_ds FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_USER_DS_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;

CREATE USER web_user_hm FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_USER_HM_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;

--LOADER

CREATE USER web_loader_pr FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_LOAD_PR_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;

CREATE USER web_loader_ds FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_LOAD_DS_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;

CREATE USER web_loader_hm FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_LOAD_HM_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;

--BKGND

CREATE USER web_bkgnd_pr FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_LOAD_PR_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;

CREATE USER web_bkgnd_ds FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_LOAD_DS_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;

CREATE USER web_bkgnd_hm FROM MDW_WEB_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_LOAD_HM_RL ,PROFILE = MDW_WEB_PRF, DATEFORM = ANSIDATE;


/* Permisos a SysDBA . German 2016-10-02 */

-- Profile y Roles
GRANT 
CREATE PROFILE, 
DROP PROFILE,
CREATE ROLE,
DROP ROLE
TO SysDBA WITH GRANT OPTION;

--Users
GRANT 
CREATE USER, 
DROP USER
ON MDW_USERS TO SysDBA WITH GRANT OPTION;

/* Profile de desarrollo */

CREATE PROFILE MDW_DEVELOPER_PRF AS SPOOL = 1000000000 BYTES; -- 1. GB.

/* Base de Usuarios de desarrollo */

CREATE USER MDW_DEVELOPER_USERS FROM MDW_USERS AS PERM = 0, PASSWORD = ******** ;

/* Rol de web */
CREATE ROLE MDW_DEVELOPER_RL;

/* Usuarios de desarrollo */
CREATE USER german_schauvinhold FROM MDW_DEVELOPER_USERS AS PERM = 0, PASSWORD = ********	 , DEFAULT ROLE = MDW_DEVELOPER_RL ,PROFILE = MDW_DEVELOPER_PRF, DATEFORM = ANSIDATE;


/* Permisos a los usuarios por el role */

GRANT

CREATE PROCEDURE,
CREATE MACRO,
CREATE TABLE,
CREATE VIEW,

DROP PROCEDURE,
DROP MACRO,
DROP TABLE,
DROP VIEW,

EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE

ON MDW_DS_STG TO MDW_DEVELOPER_RL;


GRANT

CREATE PROCEDURE,
CREATE MACRO,
CREATE TABLE,
CREATE VIEW,

DROP PROCEDURE,
DROP MACRO,
DROP TABLE,
DROP VIEW,

EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE

ON MDW_DS_TABLES TO MDW_DEVELOPER_RL;


GRANT

CREATE PROCEDURE,
CREATE MACRO,
CREATE TABLE,
CREATE VIEW,

DROP PROCEDURE,
DROP MACRO,
DROP TABLE,
DROP VIEW,

EXECUTE,
INSERT,
SELECT,
UPDATE,
DELETE

ON MDW_DS_VIEWS TO MDW_DEVELOPER_RL;




/* Permisos para crear y ejecutar funciones para calculo de minimo. Gerardo 2013-09-04 */

--Como DBC ejecutar el siguiente comando
GRANT EXECUTE FUNCTION ON TD_SYSFNLIB TO SYSDBA WITH GRANT OPTION;

--Como SYSDBA.
GRANT EXECUTE FUNCTION ON CDW_R01_DS TO CDW_REPL_USER_DS_RL; --Execute al rol de desarrollo.
GRANT EXECUTE FUNCTION ON CDW_R01_DS TO CDW_REPL_LOAD_DS_RL; --Para loader

GRANT EXECUTE FUNCTION ON CDW_R01 TO CDW_REPL_USER_RL; --Execute al rol de produccion.
GRANT EXECUTE FUNCTION ON CDW_R01 TO CDW_REPL_LOAD_RL;

GRANT EXECUTE FUNCTION ON CDW_R01_HM_DEV TO CDW_REPL_USER_HM_DEV_RL; --Execute al rol de produccion.
GRANT EXECUTE FUNCTION ON CDW_R01_HM_DEV TO CDW_REPL_LOAD_HM_DEV_RL;

--para el lock for exclusive para cargas
GRANT DROP TABLE ON CDW_R01_HM.RepFileProcessQueueLockAccess TO CDW_REPL_LOAD_HM_RL;
GRANT DROP TABLE ON CDW_R01_HM_DEV.RepFileProcessQueueLockAccess TO CDW_REPL_LOAD_HM_DEV_RL;

GRANT 
CREATE PROCEDURE,
EXECUTE PROCEDURE,
CREATE FUNCTION,
EXECUTE FUNCTION 
ON REPL_BKGND_HM TO SYSDBA;

